stages:
  ingest:
    cmd: python pipelines/ingest.py --src data/raw_docs --out data/clean_docs
    deps: [pipelines/ingest.py, data/raw_docs]
    outs: [data/clean_docs]
  embed:
    cmd: python pipelines/embed.py --inp data/clean_docs --out 
      data/embeddings.parquet
    deps:
    - pipelines/embed.py
    - data/clean_docs
    outs:
    - data/embeddings.parquet
